config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  root to: 'phrases#index', as: :root

  resources :phrases do
    member do
      post :vote
    end
    resources :examples, only: %i[create destroy] do
      post :vote
    end
  end

  resources :notification, only: :index do
    collection do
      put :read_all
    end
  end

  resources :users, only: %i[index show]
end

app/views/layouts/_navbar.slim
header.navbar.navbar-inverse
  .container
    nav
      a href="../"
        .logo Engli Leviossa
      ul.nav.navbar-nav.pull-right
        li
        - if signed_in?
          li = link_to "Home", root_path
          li = link_to "Users", users_path
          li.dropdown
            a.dropdown-toggle href="#" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"
              .div.likes
                ' User &nbsp
                - if current_user.has_new_notifications?
                  .div 💌 &nbsp
                span.caret
            ul.dropdown-menu
              li = link_to "View Profile", user_path(current_user)
              li = link_to "Edit Profile", edit_user_registration_path
              li = link_to notification_index_path do
                - if current_user.has_new_notifications?
                  .div.likes
                    .div 💌 &nbsp
                    ' Notifications
              li = link_to "Sign Out", destroy_user_session_path, method: "get"
        - else
          li = link_to "Sign In", new_user_session_path
          li = link_to "Sign Up", new_user_registration_path

app/views/layouts/application.slim
doctype html
html
  head
    title Rails Engli
    = stylesheet_link_tag    "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application", 'data-turbolinks-track' => true
    = csrf_meta_tag
    link rel="icon" href=""

  body.container-fluid
    .row
      = render 'layouts/navbar'
      .col-md-6.col-md-offset-3
        - flash.each do |key, value|
          div class="alert alert-#{key}"
            = value

        = yield